export const styles = {
  container: 'max-w-6xl mx-auto p-8 font-sans',
  title: 'text-5xl font-bold text-gray-900 text-center mb-8 border-b-4 border-blue-500 pb-4',
  section: 'bg-white border border-gray-200 rounded-lg p-6 mb-8 shadow-md',
  sectionTitle: 'text-2xl font-semibold text-gray-800 mb-4 pb-2 border-b-2 border-gray-100',
  addressInfo: 'bg-gray-50 p-4 rounded-md border-l-4 border-blue-500',
  addressInfoText: 'my-2 text-gray-700',
  inputGroup: 'flex flex-col gap-4 mb-4',
  input: 'p-3 border-2 border-gray-200 rounded-md text-base transition-colors focus:outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-200',
  textarea: 'p-3 border-2 border-gray-200 rounded-md text-base font-mono resize-y transition-colors focus:outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-200',
  button: 'px-6 py-3 bg-blue-500 text-white border-none rounded-md text-base font-semibold cursor-pointer transition-all hover:bg-blue-600 hover:-translate-y-0.5 hover:shadow-lg disabled:bg-gray-500 disabled:cursor-not-allowed disabled:transform-none disabled:shadow-none self-start',
  response: 'p-4 rounded-md border-l-4',
  success: 'bg-green-100 border-green-500 text-green-800',
  error: 'bg-red-100 border-red-500 text-red-800',
  responseText: 'my-2',
  jsonData: 'bg-gray-50 p-4 rounded border border-gray-200 font-mono text-sm overflow-x-auto whitespace-pre-wrap break-words',
};
