export const styles = {
  container: 'w-full max-w-4xl mx-auto p-4',
  title: 'text-2xl font-bold text-brand-black mb-6 text-center',
  dateSelector: 'mb-6 flex items-center gap-3',
  dateLabel: 'text-sm font-medium text-brand-dark-gray',
  dateSelect: 'text-sm px-3 py-2 border border-brand-light-gray rounded-md focus:outline-none focus:ring-2 focus:ring-brand shadow-sm',
  selectedDate: 'mb-4 text-center',
  dateText: 'text-lg font-semibold text-brand',
  tableContainer: 'overflow-x-auto',
  table: 'w-full border-collapse border border-brand-light-gray',
  tableHeader: 'bg-brand-light-gray bg-opacity-20',
  tableHeaderCell: 'border border-brand-light-gray px-4 py-3 text-left font-semibold text-brand-black',
  tableRow: 'hover:bg-brand-light-blue hover:bg-opacity-30',
  tableCell: 'border border-brand-light-gray px-4 py-3',
  tableCellLeft: 'text-left',
  tableCellCenter: 'text-center',
  tableCellRight: 'text-right',
  dateHeaderRow: 'bg-brand-light-blue bg-opacity-50',
  dateHeaderCell: 'border border-brand-light-gray px-4 py-2 text-justify-center font-semibold text-brand-dark-blue text-sm',
  emptyRow: 'h-16',
  emptyCell: 'border border-brand-light-gray px-4 py-3',
  emptyCellLeft: 'text-left',
  emptyCellRight: 'text-right',
  note: 'my-6 p-4 bg-brand-white border border-brand shadow-sm rounded-lg',
  noteText: 'text-sm text-brand-dark-gray mb-2 last:mb-0'
};
