export const pageStyles = {
  indicatorWrapper: 'w-[180px] mt-8 flex items-center justify-between relative',
  indicatorLeft: 'absolute left-0 top-0 h-full flex items-center',
  indicatorRight: 'absolute right-0 top-0 h-full flex items-center',
  indicatorDots: 'flex justify-center items-center w-full',
  indicatorArrowBtn: 'bg-none border-none p-0 cursor-pointer h-6 flex items-center',
  indicatorDotBtn: 'mx-[6px]',
  book: 'flex flex-col justify-center min-h-screen mx-auto max-w-[480px] w-full bg-gray-300 relative overflow-hidden box-border items-center border-none',
  flipBook: 'flex items-center justify-center w-fit h-fit overflow-visible relative border-none',
  flex: 'flex h-full',
  introPage: 'bg-white mx-auto w-full h-[300px] flex items-center justify-center box-border',
  underlineBold: 'bg-[#DFE9F2]',
  upPoint: 'w-0 h-0 border-l-[15px] border-l-[#C24A4A] border-r-[15px] border-r-[#C24A4A] border-t-[15px] border-t-transparent border-b-[15px] border-b-[#C24A4A] ml-1/2',
  pageNum: 'bg-[#4B72A6] rounded-full w-[30px] h-[30px] text-white border-none flex items-center justify-center font-bold cursor-pointer m-[var(--padding-xs)] pl-[var(--padding-xs)]',
  pageNumDiv: 'absolute left-[calc(100%-20px)] top-[20%] flex flex-col gap-[var(--padding-sm)]',
  boldMainText: 'font-bold text-[0.9em] mt-[3vh] ml-[2.5%]',
  numCircle: 'w-[6%] h-[6%] bg-black text-white flex items-center justify-center text-[0.8em] rounded-full',
  circleAndText: 'flex mt-[3vh] ml-[2.5%]',
  smallText: 'text-[0.75em] ml-[5%]',
  generalPage: 'bg-[#4B72A6] w-full h-full flex items-start justify-start box-border relative',
  generalPageTitle: 'text-white font-bold mt-[3vh] ml-[5%]',
  insideBox: 'w-[90%] h-[80%] bg-white mt-[2.5vh] ml-0',
  blue: 'absolute w-[95%] h-[4%] bg-[#4B72A6] rounded-[30em] bottom-[2%] z-[1]',
  dangerDiv: 'absolute w-[45%] border border-black pt-[0.5vh] pb-[0.5vh] rounded-[var(--radius-lg)] ml-[23%] flex mt-[3vh]',
  text: 'w-[95%] h-[50%] pt-[25%] pl-[5%] text-center text-[0.85em]',
  goDiv: 'absolute bottom-[6.3vh] left-[65%]',
  go: 'font-bold',
  goToLink: 'flex justify-center pt-[10vh] underline',
  goToNext: 'absolute w-[30%] h-[3vh] bg-white z-[5] bottom-[1.3vh] ml-[65%]',
  left: 'w-[15%] h-full flex flex-col bg-transparent border-none shadow-none',
  firstLeftBox: 'flex-1 w-full h-[20%] bg-transparent border-r-[10px] border-r-[#D9D9D9] border-b-[3px] border-b-[#D9D9D9]',
  leftBox: 'flex-1 w-full h-[20%] bg-transparent border-t-[10px] border-t-[#D9D9D9] border-r-[10px] border-r-[#D9D9D9] border-b-[3px] border-b-[#D9D9D9]',
  lastLeftBox: 'flex-1 w-full h-[20%] bg-transparent border-t-[10px] border-t-[#D9D9D9] border-r-[10px] border-r-[#D9D9D9]',
  rightFirstOutsideBox: 'w-[87%] bg-white h-[5vh] rounded-lg ml-[6%] mt-[2vh]',
  rightFirstInsideBox: 'w-[95%] border-2 border-[#4B72A6] mx-auto mt-[2vh] rounded-lg h-[3.5vh] relative top-[0.6vh]',
  smallFont: 'font-bold text-[0.8em] flex items-center justify-center pt-[0.3vh]',
  whitePaper: 'w-[87%] bg-white ml-[6%] rounded-xl mt-[2vh] p-[2vh_4%]',
  topic: 'text-[0.8em] font-bold pb-[1vh] pt-[1vh] border-b border-gray-400 mb-[1.5vh]',
  introContent: 'text-[0.65em] pb-[1vh]',
  backPage: 'h-screen w-[1.5%] bg-gray-300 border-t border-t-gray-400 border-r border-r-gray-400 border-b border-b-gray-400 rounded-xl',
  generalWhitePage: 'bg-white w-full h-full flex items-start justify-start box-border relative',
  smallFontDiv: 'relative pb-[2vh] pt-[2vh] border-b border-b-[#e5e7eb] w-full',
  borderBottomDiv: 'border-b border-b-[#e5e7eb] py-[4vh] px-[10%] h-[38vh]',
  danger: 'text-[0.8em] font-bold w-[22%] shadow-[inset_0px_-11px_0_#EDC9C9]',
  content: 'text-[0.8em] mt-[4vh] leading-[2.5vh]',
  goInside: 'flex items-center',
  goInsideDiv: 'flex items-center flex-1 w-full h-[13%] absolute bottom-0 left-[75%]',
}
